### ISSUE TITLE
chars typed before hitting Cmd+k are shown in dialog

### ISSUE THREAD

**Issue by PhilETaylor** [OzzyCzech/cmd-dialog#1]
Loving this so far... 

A quick bug report 

1. invoke cmd+k
2. close the popup dialog
3. smash the keyboard sdfkguys
4. invoke cmd+K
5. Note that the smashed keys are in the search box, but not searched for, and overlaid the placeholder

<img width="515" alt="ScreenShot-2023-03-18-22 18 33" src="https://user-images.githubusercontent.com/400092/226143185-7eb1d615-3669-4ed9-b1d5-cb2c575565c1.png">

**Comment by OzzyCzech** [comment]
Thank you for the message, it seems that this bug is only present in Safari

**Comment by PhilETaylor** [comment]
This no longer seems to happen today using Safari.

**Comment by OzzyCzech** [comment]
Thanks, for info @PhilETaylor
