### ISSUE TITLE
hotkeys (again) not overriding browser default keys

### ISSUE THREAD

**Issue by PhilETaylor** [OzzyCzech/cmd-dialog#5]
set a hotkey for and item for `cmd+n`

attempt to use `cmd+n`

It opens a new browser window, when it should trigger the action/url from the item

The hotkeys docs https://github.com/jaywcjlove/hotkeys#defining-shortcuts state you should be able to return false to override browser default behaviour, I tried that in your source code and it did not work either, you are already having `event.preventDefault()` in your code.. Im no JS expert sorry, Im mainly PHP :) 

```js
// Returning false stops the event and prevents default browser events
// Mac OS system defines `command + r` as a refresh shortcut
hotkeys('ctrl+r, command+r', function() {
  alert('stopped reload!');
  return false;
});
```

**Comment by PhilETaylor** [comment]
This is repeatable in the demo here where you have homepage set as `cmd+h` but when pressing that, the browser window "hides" as thats the browser keystroke - and for some reason hotkeys is not overruling it.

**Comment by PhilETaylor** [comment]
Im going to close this. Having spent an hour looking through hotkeys issue list in their gitrepo it looks like most of these are upstream bugs, and bugs interacting with safari :-( 

Hotkeys promises so much... it's just a little lacking at the moment.

**Comment by OzzyCzech** [comment]
There are few other libs to consider for keyboard handling:

* https://github.com/madrobby/keymaster
* https://github.com/ccampbell/mousetrap

I will try them, all are really old (~10-12 years) mousetrap seems most liked and used, I will check it

**Comment by PhilETaylor** [comment]
I have used mousetrap in other projects successfully. They all have their annoying bugs and like you say, most of them are wildly out of date and unsupported nowadays with tonnes of bugs reported and unaddressed.

There really is space for an amazing new project for keyboard binding. Im mainly a PHP dev, but I dabble in JS, but as always lack of time is the problem :)
