### ISSUE TITLE
Dark mode - icons not visible

### ISSUE THREAD

**Issue by PhilETaylor** [OzzyCzech/cmd-dialog#6]
When the theme is `dark` the chosen icons are black on dark background making them hard to see. 

<img width="763" alt="ScreenShot-2023-05-19-10 21 28" src="https://github.com/OzzyCzech/cmd-dialog/assets/400092/000232fe-4225-4962-b297-5c3ad2487302">

**Comment by OzzyCzech** [comment]
There should be `fill="currentColor"` or `stroke="currentColor"` parameter for every icon that you use.

Check for example https://heroicons.com/

```
<svg
  xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" 
  stroke-width="1.5"
  stroke="currentColor"
  class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 5.25h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5m-16.5 4.5h16.5" />
</svg>
```

**Comment by PhilETaylor** [comment]
Awesome - that works perfectly. Using fontawesome icon svgs and just pasting in ` fill="currentColor"` fixes this

To be clear, not looking for support :-) Happy to sponsor as well (although I see no sponsor button for your GitHub account?) 

<img width="448" alt="ScreenShot-2023-05-19-10 33 11" src="https://github.com/OzzyCzech/cmd-dialog/assets/400092/f0a5df94-31b4-4088-9f04-377129dfc5c7">
