### ISSUE TITLE
Dark mode not init

### ISSUE THREAD

**Issue by PhilETaylor** [OzzyCzech/cmd-dialog#7]
So I have been trying to track this down, if I set my whole Mac to use dark mode, and `window.matchMedia("(prefers-color-scheme: dark)").matches` evaluates to true in the JS Console, the dialog is still not correctly setting the dark theme

Replicated on https://cmd-dialog.vercel.app

<img width="1664" alt="ScreenShot-2023-05-19-10 28 48" src="https://github.com/OzzyCzech/cmd-dialog/assets/400092/598ee023-4fd7-42c5-bb08-286602768676">

**Comment by OzzyCzech** [comment]
Yeah, that's correct there was `theme="light"` set

**Comment by OzzyCzech** [comment]
Now it's fixed and set from system preferences

**Comment by PhilETaylor** [comment]
Awesome - I'll give it a go. Thanks again.
